// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $datenschutz from "./routes/datenschutz.tsx";
import * as $deeplink from "./routes/deeplink.tsx";
import * as $fasting from "./routes/fasting.tsx";
import * as $impressum from "./routes/impressum.tsx";
import * as $index from "./routes/index.tsx";
import * as $paren from "./routes/paren.tsx";
import * as $sync from "./routes/sync.tsx";
import * as $CountdownClock from "./islands/CountdownClock.tsx";
import * as $DeeplinkButton from "./islands/DeeplinkButton.tsx";
import * as $SyncButton from "./islands/SyncButton.tsx";
import * as $fasting_widget from "./islands/fasting_widget.tsx";
import * as $index_1 from "./islands/index.tsx";
import * as $paren_flutter from "./islands/paren_flutter.tsx";
import * as $snowfall from "./islands/snowfall.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/datenschutz.tsx": $datenschutz,
    "./routes/deeplink.tsx": $deeplink,
    "./routes/fasting.tsx": $fasting,
    "./routes/impressum.tsx": $impressum,
    "./routes/index.tsx": $index,
    "./routes/paren.tsx": $paren,
    "./routes/sync.tsx": $sync,
  },
  islands: {
    "./islands/CountdownClock.tsx": $CountdownClock,
    "./islands/DeeplinkButton.tsx": $DeeplinkButton,
    "./islands/SyncButton.tsx": $SyncButton,
    "./islands/fasting_widget.tsx": $fasting_widget,
    "./islands/index.tsx": $index_1,
    "./islands/paren_flutter.tsx": $paren_flutter,
    "./islands/snowfall.tsx": $snowfall,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
