// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $datenschutz from "./routes/datenschutz.tsx";
import * as $impressum from "./routes/impressum.tsx";
import * as $index from "./routes/index.tsx";
import * as $NewYear from "./islands/NewYear.tsx";
import * as $about from "./islands/about.tsx";
import * as $ai_chat from "./islands/ai_chat.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/datenschutz.tsx": $datenschutz,
    "./routes/impressum.tsx": $impressum,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/NewYear.tsx": $NewYear,
    "./islands/about.tsx": $about,
    "./islands/ai_chat.tsx": $ai_chat,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
